config/routes.rb
Rails.application.routes.draw do
 
  
  
  
  namespace :api do
    namespace :v1 do
      
      resources :setups
      resources :types 
      resources :weapons do
        resources :hip_fires, module: :weapons
        resources :canons do
          resources :canon_recoils
          resources :hip_fires, module: :canons
        end
        resources :muzzles do
            resources :muzzle_recoils
            resources :hip_fires, module: :muzzles
        end
        resources :lasers do
          resources :laser_recoils
          resources :hip_fires, module: :lasers
        end
        resources :optics do 
          resources :optic_recoils
          resources :hip_fires, module: :optics
        end 
        resources :stocks do
          resources :stock_recoils
          resources :hip_fires, module: :stocks
        end
        resources :underbarrels do
          resources :underbarrel_recoils
          resources :hip_fires, module: :underbarrels
        end
        resources :munitions do
          resources :munition_recoils
          resources :hip_fires, module: :munitions
        end
        resources :grips do
          resources :grip_recoils
          resources :hip_fires, module: :grips
        end
        resources :perks
        resources :recoils
      end
    end
  end
  
resources :blogs
devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: "blogs#index"
 get '/admin', to: "pages#admin"
 get '/warzone-weapons-builder', to: "pages#reactor"
 get 'api/v1/user', to: "pages#user"
 get '/table', to: "pages#table"

#  get '*path', to: "pages#reactor" 
end
  

app/models/blog.rb
class Blog < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    validates :title, presence: true
    validates :description, presence: true
    validates :illustration, presence: true
    has_one_attached :illustration
    has_one_attached :image_1
    has_rich_text :body
    

end

app/models/canon.rb
class Canon < ApplicationRecord
  belongs_to :weapon
  has_many :canon_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/canon_recoil.rb
class CanonRecoil < ApplicationRecord
    belongs_to :canon
end

app/models/grip.rb
class Grip < ApplicationRecord
  belongs_to :weapon
  has_many :grip_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/grip_recoil.rb
class GripRecoil < ApplicationRecord
    belongs_to :grip
end

app/models/hip_fire.rb
class HipFire < ApplicationRecord
  belongs_to :hipfireable, polymorphic: true

  validates :xaxis, presence: true
  validates :yaxis, presence: true
end

app/models/laser.rb
class Laser < ApplicationRecord
  belongs_to :weapon
  has_many :laser_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/laser_recoil.rb
class LaserRecoil < ApplicationRecord
    belongs_to :laser
end

app/models/munition.rb
class Munition < ApplicationRecord
  belongs_to :weapon
  has_many :munition_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/muzzle.rb
class Muzzle < ApplicationRecord
  belongs_to :weapon
  has_many :muzzle_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/optic.rb
class Optic < ApplicationRecord
  belongs_to :weapon
  has_many :optic_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/optic_recoil.rb
class OpticRecoil < ApplicationRecord
    belongs_to :optic
end

app/models/perk.rb
class Perk < ApplicationRecord
  belongs_to :weapon
  has_many :hip_fires, as: :hipfireable

end

app/models/recoil.rb
class Recoil < ApplicationRecord
    belongs_to :weapon
end

app/models/setup.rb
class Setup < ApplicationRecord

    validates :name, presence: true
    validates :ads_time, numericality: {less_than_or_equal_to: 0}
    validates :hip_fire_cone, numericality: {less_than_or_equal_to: 0}
    validates :sprint_to_fire, numericality: {less_than_or_equal_to: 0}
    validates :bounce, numericality: {less_than_or_equal_to: 0}
    validates :vertical_recoil, numericality: {less_than_or_equal_to: 0}
    validates :horizontal_recoil, numericality: {less_than_or_equal_to: 0}
    validates :vertical_recoil_first_10, numericality: {less_than_or_equal_to: 0}
    validates :horizontal_recoil_first_10, numericality: {less_than_or_equal_to: 0}
    validates :vertical_recoil_first_20, numericality: {less_than_or_equal_to: 0}
    validates :horizontal_recoil_first_20, numericality: {less_than_or_equal_to: 0}
    validates :reload_time, numericality: {less_than_or_equal_to: 0}
    
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :weapon
  has_many :stock_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/stock_recoil.rb
class StockRecoil < ApplicationRecord
    belongs_to :stock
end

app/models/type.rb
class Type < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :weapons, dependent: :destroy

end

app/models/underbarrel.rb
class Underbarrel < ApplicationRecord
  belongs_to :weapon
  has_many :underbarrel_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable



end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :hip_fires, as: :hipfireable

  belongs_to :type
  has_many :canons, dependent: :destroy
  has_many :muzzles, dependent: :destroy
  has_many :lasers, dependent: :destroy
  has_many :optics, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :underbarrels, dependent: :destroy
  has_many :munitions, dependent: :destroy
  has_many :grips, dependent: :destroy
  has_many :perks, dependent: :destroy
  has_many :recoils, dependent: :destroy

  validates :type_id, presence: true
  validates :name, presence: true
  validates :ads_time, numericality: {less_than_or_equal_to: 0}
  validates :hip_fire_cone, numericality: {less_than_or_equal_to: 0}
  validates :sprint_to_fire, numericality: {less_than_or_equal_to: 0}
  validates :bounce, numericality: {less_than_or_equal_to: 0}
  validates :vertical_recoil, numericality: {less_than_or_equal_to: 0}
  validates :horizontal_recoil, numericality: {less_than_or_equal_to: 0}
  validates :vertical_recoil_first_10, numericality: {less_than_or_equal_to: 0}
  validates :horizontal_recoil_first_10, numericality: {less_than_or_equal_to: 0}
  validates :vertical_recoil_first_20, numericality: {less_than_or_equal_to: 0}
  validates :horizontal_recoil_first_20, numericality: {less_than_or_equal_to: 0}
  validates :reload_time, numericality: {less_than_or_equal_to: 0}
 

  has_one_attached :image
  has_rich_text :content
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :admincheck, only: [:new, :create, :edit, :update, :destroy]
 

  POSTS_PER_PAGE = 12

  def index
    @page = params.fetch(:page, 0).to_i
    if @page < 0
      @page = 0
    end 
    @blogs = Blog.where(featured: 0).order(created_at: :desc).offset(@page * POSTS_PER_PAGE).limit(POSTS_PER_PAGE) 
    @bigfeature = Blog.where(featured: 1).last
    @smalltopfeature = Blog.where(featured: 2).last
    @smallbotfeature = Blog.where(featured: 3).last

  end
  
  def new
    @blog = Blog.new
  end

  def create
  @blog = Blog.new(blog_params)
    if @blog.save 
      redirect_to root_path
    else
      render "new", alert: @blog.errors.full_messages     
    end
  end

  def show
    @blog = Blog.friendly.find(params[:id])
  end

  def edit
    @blog = Blog.friendly.find(params[:id])
  end

  def update
    @blog = Blog.friendly.find(params[:id])
    if @blog.update(blog_params)
      redirect_to root_path
    else
      redirect_to edit_blog_path(@blog), alert: @blog.errors.full_messages     
    end
  end

  def destroy
    @blog = Blog.friendly.find(params[:id])
    @blog.destroy 
    redirect_to blogs_path
  end

 private 
 
 def blog_params
  params.require(:blog).permit(:title, :text_area_1, :illustration, :image_1, :featured, :description, :show_illustration, :body)
 end


 
end

app/helpers/blogs_helper.rb
module BlogsHelper


    
end

app/views/blogs/edit.html.erb
<h1 class="text-center">Edit a post </h1>
<div class="row">
    <div class="col-md-10 offset-1">
<%=  form_with model: @blog, local: true do |f| %>

   <div class="form-group">
          <%= f.label :title, "title" %>
          <%= f.text_field :title, {class: "form-control", placeholder: "your title"} %>
 </div>

  <div class="form-group">
          <%= f.label :description, "short description" %>
          <%= f.text_area :description, {class: "form-control", placeholder: "short description"} %>
 </div>

 <div class="form-group">
          <%= f.label :featured, "featured" %>
          <%= f.number_field :featured, {class: "form-control", placeholder: "make featured"} %>
 </div>

 <div class="form-group">
          <%= f.label :text_area_1, "text area 1" %>
          <%= f.text_area :text_area_1, {class: "form-control", placeholder: "your text"} %>
 </div>

<div class="form-group">
          <%= f.label :body, "Trix body" %>
          <%= f.rich_text_area :body %>
 </div>

<div class="form-group">
          <%= image_tag(@blog.illustration, height: '300' , width: '300') %>
          <%= f.label :illustration, "image " %>
          <%= f.file_field :illustration %>
 </div>

 <div class="form-group">
          <%= f.label :show_illustration, "show illustration ? (default yes) " %>
          <%= f.check_box :show_illustration %>
</div>
        

 <div class="form-group">

          <%= @blog.image_1.attached? && image_tag(@blog.image_1, height: '300' , width: '300') %>
          <%= f.label :image_1, "image " %>
          <%= f.file_field :image_1 %>
 </div>

 <div class="form-group">
        
       <%= f.submit "save ", class: "btn btn-outline-info btn-block"%> 
</div>

<% end %>

app/views/blogs/index.html.erb
 <% provide(:title, "Warzone News") %>
 
 <% if user_signed_in? && current_user.admin %>
  <div class="row ">
    <div class="col admin-bar">
      <div>
        <%= link_to new_blog_path do  %>
          <button class="btn btn-info"> Add post</button>
        <% end %>
      </div>
      <% if @bigfeature %>
        <div>
          <%= link_to edit_blog_path(@bigfeature) do  %>
            <button class="btn btn-info">  Edit Jumbo</button>
          <% end %>
          <%= link_to blog_path(@bigfeature), method: :delete, data: {confirm: "are you sure ???"} do  %>
            <button class="btn btn-danger"> Delete Jumbo </button>
          <% end %>
        </div>
      <% end %>
      <% if @smalltopfeature %>
        <div>
          <%= link_to edit_blog_path(@smalltopfeature) do  %>
            <button class="btn btn-info">  Edit Small Top Feature</button>
          <% end %>
          <%= link_to blog_path(@smalltopfeature), method: :delete, data: {confirm: "are you sure ???"} do  %>
            <button class="btn btn-danger"> Delete Small Top Feature </button>
          <% end %>
        </div>
      <% end %>
      <% if @smallbotfeature %>
        <div>
          <%= link_to edit_blog_path(@smallbotfeature) do  %>
            <button class="btn btn-info">  Edit Small Bot Feature</button>
          <% end %>
          <%= link_to blog_path(@smallbotfeature), method: :delete, data: {confirm: "are you sure ???"} do  %>
            <button class="btn btn-danger"> Delete Small Bot Feature </button>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-lg-10 offset-lg-1 col-12">
    <div class="row">
      <div class="col-lg-8 col-8">
        <% if @bigfeature %>
          <div class="jumbo-box">
            <%= link_to  blog_path(@bigfeature) do %>
              <%= image_tag( @bigfeature.illustration.variant(resize_to_fill: [1030,580], quality: 50), class: "img-fluid big-card") %>
              <h1 class="carousel-caption big-text"> <%= @bigfeature.title %> <br>
                <span class="small-text"> <%= @bigfeature.description %></span>
              </h1>
            <% end %>
          </div >
        <% else %>
          <%= image_tag( "season2Meta.jpg", class: "img-fluid big-card") %>
        <% end %>
      </div>
      <div class="col-lg-4 col-4">
        <% if @smalltopfeature %>
          <div class="jumbo-box">
            <%= link_to  blog_path(@smalltopfeature) do %>
              <%= image_tag(@smalltopfeature.illustration.variant(resize_to_fill: [500,279], quality: 50), class: "img-fluid big-card first-one") %>
              <h1 class="carousel-caption big-text" id="top-text"> <%= @smalltopfeature.title %> <br>
                <span class="small-text"> <%= @smalltopfeature.description %></span>
              </h1>
            <% end %>
          </div >
        <% else %>
          <%= image_tag("Call-of-Duty-warzone-3.jpg", class: "img-fluid big-card first-one") %>
        <%end %>
        <div class="row spacing-row">
          <div class="col">
            <% if @smallbotfeature %>
              <div class="jumbo-box">
                <%= link_to  blog_path(@smallbotfeature) do %>
                  <%= image_tag(@smallbotfeature.illustration.variant(resize_to_fill: [500,279], quality: 50), class: "img-fluid big-card first-one") %>
                  <h1 class="carousel-caption big-text" id="top-text"> <%= @smallbotfeature.title %> <br>
                    <span class="small-text"> <%= @smallbotfeature.description %></span>
                  </h1>
                <% end %>
              </div >
            <% else %>
              <%= image_tag( "Call-of-Duty-warzone-3.jpg", class: "img-fluid big-card") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <% @blogs.each do |b| %>
        <div class="col-lg-3 col-6 no-link-decoration">
          <%= link_to blog_path(b) do  %>
            <div class="card  mini-card">
              <%= image_tag(b.illustration.variant(resize_to_fill: [300, 200], quality: 50), class: "card-img-top") %>
              <div class="card-body body-css">
                <h5 class="card-title"> <%= b.title %></h5>
                <p class="card-text "><%= b.description %></p>
                <p class="card-text ">  <%= b.created_at.strftime("Posted the : %m/%d/%Y")%></p>

                <% if user_signed_in? && current_user.admin %>
                  <div>
                    <%= link_to  edit_blog_path(b) do %>
                      <button class="btn btn-info"> Edit </button>
                    <% end %>
                    <%= link_to  blog_path(b), method: :delete, data: {:confirm => "are you sure ???"} do %>
                      <button class="btn btn-danger"> Destroy </button>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
<div class ="row">
  <div class ="col-12" id="paginate-links">
    <% if @page > 0 %>
      <%= link_to  "previous page", blogs_path(page: @page - 1 ) %>
      |
    <% end %>
    <%= link_to  "next page", blogs_path(page: @page + 1 ) %>
  </div>
</div>

app/views/blogs/new.html.erb
<h1 class="text-center">Create a new post </h1>
<div class="row">
    <div class="col-md-10 offset-1">
<%=  form_with model: @blog, local: true do |f| %>
<% if @blog.errors.any? %>
    <ul>
            <%@blog.errors.full_messages.each do |error|%>

        <li style="color: red"><%= error %> </li>
        <% end %>
    </ul>
<% end %>

   <div class="form-group">
          <%= f.label :title, "title" %>
          <%= f.text_field :title, {class: "form-control", placeholder: "make title"} %>
 </div>

 <div class="form-group">
          <%= f.label :description, "short description" %>
          <%= f.text_area :description, {class: "form-control", placeholder: "short description"} %>
 </div>



 <div class="form-group">
          <%= f.label :featured, "featured  0 = no featured , 1 = jumbo, 2 = top right, 3 = bottom right" %>
          <%= f.number_field :featured, {class: "form-control", placeholder: "make featured"} %>
 </div>

 <div class="form-group">
          <%= f.label :text_area_1, "Text area 1" %>
          <%= f.text_area :text_area_1, {class: "form-control", placeholder: "your text"} %>
 </div>

<div class="form-group">
          <%= f.label :body, "Trix body" %>
          <%= f.rich_text_area :body %>
 </div>

<div class="form-group">
          <%= f.label :illustration, "illustration " %>
          <%= f.file_field :illustration %>
 </div>

<div class="form-group">
          <%= f.label :show_illustration, "show illustration ? (default yes) " %>
          <%= f.check_box :show_illustration %>
</div>
        
 <div class="form-group">
          <%= f.label :image_1, "image 1" %>
          <%= f.file_field :image_1 %>
 </div>

 <div class="form-group">
        
       <%= f.submit "save " , class: "btn btn-outline-info btn-block"%> 
</div>

<% end %>

app/views/blogs/show.html.erb
<% provide(:title, @blog.title )%>
<% if user_signed_in? && current_user.admin %>
  <div class="row  admin-bar">
    <div class="col show-admin">
      <%= link_to new_blog_path do  %>
        <button class="btn btn-primary show-admin-button"> Add post</button>
      <% end %>
     

      
      <%= link_to edit_blog_path(@blog) do  %>
        <button class="btn btn-info show-admin-button"> Edit post</button>
      <% end %>
     

        
      <%= link_to blog_path(@blog), method: :delete, data: {confirm: "are you sure ?"} do  %>
        <button class="btn btn-danger show-admin-button"> Destroy post</button>
      <% end %>
      </div> 
    </div>
<% end %>


<div class="row">
  <div class="col-12 ">
    <div class="image-container">
    <% if @blog.show_illustration %>
    <%= image_tag(@blog.illustration.variant(resize_to_fill: [800,400], quality: 100), class: "img-fluid title-image-show") %>
    <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-12">
    <h1 class="title-blog-show"> <%= @blog.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-8 offset-lg-2 col-12">
        <p class="date-blog-show">  <%= @blog.created_at.strftime("Posted the : %m/%d/%Y")%></p>
  </div>
</div>


<br><br><br>
<div class="row">
  <div class="col-lg-6 offset-lg-3 col-12">
    <div class="text-area-show"> <%= @blog.text_area_1.html_safe %></div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <% if @blog.image_1.attached?  %>
    <div class="image-container">
      <%=  image_tag(@blog.image_1.variant(resize_to_fill: [600, 600], quality: 50), class: "img-fluid") %>
      </div >
    <% end %>
  </div>
</div>

<div class="container body-style">

  <%= @blog.body %>
</div>


<div class="row">
  <div class="col-lg-8 offset-lg-2">
<div id="disqus_thread" class="disqus-placement"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    
    var disqus_config = function () {
    this.page.url = '<%= url_for(controller: 'blogs', action: 'show', only_path: false) %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @blog.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://warzoneweapons.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
</div>