config/routes.rb
Rails.application.routes.draw do
 
  
  
  
  namespace :api do
    namespace :v1 do
      
      resources :setups
      resources :types 
      resources :weapons do
        resources :hip_fires, module: :weapons
        resources :canons do
          resources :canon_recoils
          resources :hip_fires, module: :canons
        end
        resources :muzzles do
            resources :muzzle_recoils
            resources :hip_fires, module: :muzzles
        end
        resources :lasers do
          resources :laser_recoils
          resources :hip_fires, module: :lasers
        end
        resources :optics do 
          resources :optic_recoils
          resources :hip_fires, module: :optics
        end 
        resources :stocks do
          resources :stock_recoils
          resources :hip_fires, module: :stocks
        end
        resources :underbarrels do
          resources :underbarrel_recoils
          resources :hip_fires, module: :underbarrels
        end
        resources :munitions do
          resources :munition_recoils
          resources :hip_fires, module: :munitions
        end
        resources :grips do
          resources :grip_recoils
          resources :hip_fires, module: :grips
        end
        resources :perks
        resources :recoils
      end
    end
  end
  
resources :blogs
devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: "blogs#index"
 get '/admin', to: "pages#admin"
 get '/warzone-weapons-builder', to: "pages#reactor"
 get 'api/v1/user', to: "pages#user"
 get '/table', to: "pages#table"

#  get '*path', to: "pages#reactor" 
end
  

app/models/blog.rb
class Blog < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    validates :title, presence: true
    validates :description, presence: true
    validates :illustration, presence: true
    has_one_attached :illustration
    has_one_attached :image_1
    has_rich_text :body
    

end

app/models/canon.rb
class Canon < ApplicationRecord
  belongs_to :weapon
  has_many :canon_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/canon_recoil.rb
class CanonRecoil < ApplicationRecord
    belongs_to :canon
end

app/models/grip.rb
class Grip < ApplicationRecord
  belongs_to :weapon
  has_many :grip_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/grip_recoil.rb
class GripRecoil < ApplicationRecord
    belongs_to :grip
end

app/models/hip_fire.rb
class HipFire < ApplicationRecord
  belongs_to :hipfireable, polymorphic: true

  validates :xaxis, presence: true
  validates :yaxis, presence: true
end

app/models/laser.rb
class Laser < ApplicationRecord
  belongs_to :weapon
  has_many :laser_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/laser_recoil.rb
class LaserRecoil < ApplicationRecord
    belongs_to :laser
end

app/models/munition.rb
class Munition < ApplicationRecord
  belongs_to :weapon
  has_many :munition_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/muzzle.rb
class Muzzle < ApplicationRecord
  belongs_to :weapon
  has_many :muzzle_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/optic.rb
class Optic < ApplicationRecord
  belongs_to :weapon
  has_many :optic_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/optic_recoil.rb
class OpticRecoil < ApplicationRecord
    belongs_to :optic
end

app/models/perk.rb
class Perk < ApplicationRecord
  belongs_to :weapon
  has_many :hip_fires, as: :hipfireable

end

app/models/recoil.rb
class Recoil < ApplicationRecord
    belongs_to :weapon
end

app/models/setup.rb
class Setup < ApplicationRecord

    validates :name, presence: true
    validates :ads_time, numericality: {less_than_or_equal_to: 0}
    validates :hip_fire_cone, numericality: {less_than_or_equal_to: 0}
    validates :sprint_to_fire, numericality: {less_than_or_equal_to: 0}
    validates :bounce, numericality: {less_than_or_equal_to: 0}
    validates :vertical_recoil, numericality: {less_than_or_equal_to: 0}
    validates :horizontal_recoil, numericality: {less_than_or_equal_to: 0}
    validates :vertical_recoil_first_10, numericality: {less_than_or_equal_to: 0}
    validates :horizontal_recoil_first_10, numericality: {less_than_or_equal_to: 0}
    validates :vertical_recoil_first_20, numericality: {less_than_or_equal_to: 0}
    validates :horizontal_recoil_first_20, numericality: {less_than_or_equal_to: 0}
    validates :reload_time, numericality: {less_than_or_equal_to: 0}
    
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :weapon
  has_many :stock_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/type.rb
class Type < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :weapons, dependent: :destroy

end

app/models/underbarrel.rb
class Underbarrel < ApplicationRecord
  belongs_to :weapon
  has_many :underbarrel_recoils
  has_many :hip_fires, as: :hipfireable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable



end

app/models/weapon.rb
class Weapon < ApplicationRecord
  has_many :hip_fires, as: :hipfireable

  belongs_to :type
  has_many :canons, dependent: :destroy
  has_many :muzzles, dependent: :destroy
  has_many :lasers, dependent: :destroy
  has_many :optics, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :underbarrels, dependent: :destroy
  has_many :munitions, dependent: :destroy
  has_many :grips, dependent: :destroy
  has_many :perks, dependent: :destroy
  has_many :recoils, dependent: :destroy

  validates :type_id, presence: true
  validates :name, presence: true
  validates :ads_time, numericality: {less_than_or_equal_to: 0}
  validates :hip_fire_cone, numericality: {less_than_or_equal_to: 0}
  validates :sprint_to_fire, numericality: {less_than_or_equal_to: 0}
  validates :bounce, numericality: {less_than_or_equal_to: 0}
  validates :vertical_recoil, numericality: {less_than_or_equal_to: 0}
  validates :horizontal_recoil, numericality: {less_than_or_equal_to: 0}
  validates :vertical_recoil_first_10, numericality: {less_than_or_equal_to: 0}
  validates :horizontal_recoil_first_10, numericality: {less_than_or_equal_to: 0}
  validates :vertical_recoil_first_20, numericality: {less_than_or_equal_to: 0}
  validates :horizontal_recoil_first_20, numericality: {less_than_or_equal_to: 0}
  validates :reload_time, numericality: {less_than_or_equal_to: 0}
 

  has_one_attached :image
  has_rich_text :content
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Warzone Weapons </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/3868d46130.js" crossorigin="anonymous"></script>
    <meta name="description" content="warzone weapons stats and loadout builder app, compare your weapons with the Meta !"/>
  </head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-MCLMPFG9F9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MCLMPFG9F9');
</script>


  <body class="body-app">
    <%= render "shared/nav"%>
    <%= render "shared/flash"%>
    
    <div class="container-fluid content-flex">
        <%= yield %>
    </div>


 <footer class="footer py-2 bg-light">
    <span class="text-muted">
    Copyright © 2021 Warzone Weapons. All Call of Duty references are belonging to their rightfull owner.
    All links to other website are not under our control
    <a href="mailto:warzonweapons@gmail.com">warzonweapons@gmail.com </a>
     </span>
</footer>

  </body>

 
</html>

app/views/pages/admin.html.erb
<h1> YOU ARE ADMIN :<%= @admin.email %> admin : <%= @admin.admin %></h1>


<ul>

<li>
<%= link_to  "Add  types", new_api_v1_type_path %>
</li>
<li>
<%= link_to  "Weapons console", api_v1_types_path %>
</li>

<li>
<%= link_to  "Meta Console", api_v1_setups_path %>
</li>

<li>
<%= link_to "Weapons Table exel" , table_path%>
</li>

<ul>

app/views/pages/home.html.erb
<div class="row">

    
        <div class="col">
                <h1 class="text-center"> Warzone Weapons Central  </h1>

                <img src=<%=asset_path("placeholder.jpg")%> class="img-fluid rounded" alt="warzone" /> 
            

        </div>

        
    </div>

app/views/pages/reactor.html.erb
    
    <% provide(:title, "Weapon Builder App") %>
    <div id="weaponbuilder">




    
    </div>

app/views/pages/table.html.erb
<div class="row">
  <div class="col-lg-1">
  </div>
  <div class="col-lg-10">


  <table class="table table-dark table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">RPM</th>
      <th scope="col">Magazine</th>
      <th scope="col">reload_time</th>
      <th scope="col">ads_time </th>
      <th scope="col"> sprint_to_fire</th>
      <th scope="col"> movement</th>
      <th scope="col"> ads_movement</th>
      <th scope="col">hip_fire_cone </th>
      <th scope="col">bullet_velocity </th>
      <th scope="col">bounce </th>
      <th scope="col"> vertical_recoil</th>
      <th scope="col">horizontal_recoil </th>
      <th scope="col">vertical_recoil_first_10 </th>
      <th scope="col"> horizontal_recoil_first_10</th>
      <th scope="col"> vertical_recoil_first_20</th>
      <th scope="col"> horizontal_recoil_first_20</th>
      <th scope="col">head_dmg_range_1 </th>
      <th scope="col"> chest_dmg_range_1</th>
      <th scope="col"> stomach_dmg_range_1</th>
      <th scope="col"> limbs_dmg_range_1</th>
      <th scope="col">head_dmg_range_2 </th>
      <th scope="col"> chest_dmg_range_2</th>
      <th scope="col">stomach_dmg_range_2 </th>
      <th scope="col">limbs_dmg_range_2</th>
      <th scope="col">head_dmg_range_3 </th>
      <th scope="col"> chest_dmg_range_3</th>
      <th scope="col">stomach_dmg_range_3 </th>
      <th scope="col"> limbs_dmg_range_3</th>
      <th scope="col"> head_dmg_range_4</th>
      <th scope="col">chest_dmg_range_4 </th>
      <th scope="col"> stomach_dmg_range_4</th>
      <th scope="col"> limbs_dmg_range_4</th>
      <th scope="col">range_1 </th>
      <th scope="col">range_2 </th>
      <th scope="col">range_3</th>
      <th scope="col"> range_3_used</th>
      <th scope="col">range_4 </th>
      <th scope="col"> range_4_used</th>
      <th scope="col"> burst</th>
      <th scope="col">game </th>
     
    </tr>
  </thead>
  <tbody>
 
    <% @weapons.each do |w| %>
      
        <tr>
        <th>  <%= w.name %> </th>
        <td> <%= w.rpm %></td>  
        <td> <%= w.magazine %></td>  
        <td> <%= w.reload_time %></td>  
        <td> <%= w.ads_time %></td> 
        <td> <%= w.sprint_to_fire %></td>  
        <td> <%= w.movement %></td>  
        <td> <%= w.ads_movement %></td>  
        <td> <%= w.hip_fire_cone %></td>  
        <td> <%= w.bullet_velocity %></td>  
         <td> <%= w.bounce %></td>  
        <td> <%= w.vertical_recoil %></td>  
        <td> <%= w.horizontal_recoil %></td>  
        <td> <%= w.vertical_recoil_first_10 %></td>  
        <td> <%= w.horizontal_recoil_first_10 %></td> 
        <td> <%= w.vertical_recoil_first_20 %></td>  
        <td> <%= w.horizontal_recoil_first_20 %></td>  
        <td> <%= w.head_dmg_range_1 %></td>  
        <td> <%= w.chest_dmg_range_1 %></td>  
        <td> <%= w.stomach_dmg_range_1 %></td>  
         <td> <%= w.limbs_dmg_range_1 %></td>  
        <td> <%= w.head_dmg_range_2 %></td>  
        <td> <%= w.chest_dmg_range_2 %></td>  
        <td> <%= w.stomach_dmg_range_2 %></td>  
        <td> <%= w.limbs_dmg_range_2 %></td> 
        <td> <%= w.head_dmg_range_3 %></td>  
        <td> <%= w.chest_dmg_range_3 %></td>  
        <td> <%= w.stomach_dmg_range_3 %></td>  
        <td> <%= w.limbs_dmg_range_3 %></td>  
        <td> <%= w.head_dmg_range_4 %></td>  
         <td> <%= w.chest_dmg_range_4 %></td>  
        <td> <%= w.stomach_dmg_range_4 %></td>  
        <td> <%= w.limbs_dmg_range_4 %></td>  
        <td> <%= w.range_1 %></td>  
        <td> <%= w.range_2 %></td> 
        <td> <%= w.range_3 %></td>  
        <td> <%= w.range_3_used %></td>  
        <td> <%= w.range_4 %></td>  
        <td> <%= w.range_4_used %></td>  
        <td> <%= w.burst %></td>  
        <td> <%= w.game %></td>  
        
        </tr>
      
    <% end %>
      
   
   
  </tbody>
</table>


    
  </div>
  <div class="col-lg-1">
  </div>
</div>

app/views/pages/user.html.erb
<h1>Hello <%= @admin.email %> </h1>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="container">
        <div class="alert <%= key == 'notice' ? 'alert-primary' : 'alert-danger' %>" role="alert">
            <%= value %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
<% end %>

app/views/shared/_formAttachment.html.erb
<div class="row">
<h1> MODIFIER : BONUS ARE ALWAYS POSITIVE , MALUS ARE ALWAYS NEGATIVE</h1>
  <div class="col-md-4">
<div class="form-group">
          <%= f.label :name, "Type Name" %>
          <%= f.text_field :name, {class: "form-control", placeholder: "Enter weapons name"} %>
        </div>
         
        <div class="form-group">
          <%= f.label :hip_fire_cone, "hip fire cone" %>
          <%= f.number_field :hip_fire_cone, {class: "form-control", placeholder: "hip fire cone", step: 0.01} %>
        </div>
         <div class="form-group">
          <%= f.label :ads_time, "time to ads" %>
          <%= f.number_field :ads_time, {class: "form-control", placeholder: "ads time", step: 0.01} %>
        </div>
          <div class="form-group">
          <%= f.label :sprint_to_fire, "sprint to fire" %>
          <%= f.number_field :sprint_to_fire, {class: "form-control", placeholder: "sprint to fire time", step: 0.01} %>
        </div>

         <div class="form-group">
          <%= f.label :movement, "movement speed" %>
          <%= f.number_field :movement, {class: "form-control", placeholder: "movement speed", step: 0.01} %>
        </div>
        <div class="form-group">
          <%= f.label :ads_movement, "ads_movement" %>
          <%= f.number_field :ads_movement, {class: "form-control", placeholder: "ads_movement", step: 0.01} %>
        </div>

      

        <div class="form-group">
          <%= f.label :bullet_velocity, "bullet velocity" %>
          <%= f.number_field :bullet_velocity, {class: "form-control", placeholder: "bullet velocity", step: 0.01} %>
        </div>

        <div class="form-group">
          <%= f.label :bounce, "bounce" %>
          <%= f.number_field :bounce, {class: "form-control", placeholder: "bounce", step: 0.01} %>
        </div>
        <div class="form-group">
          <%= f.label :vertical_recoil, "vertical recoil" %>
          <%= f.number_field :vertical_recoil, {class: "form-control", placeholder: "vertical recoil", step: 0.01} %>
        </div>
        <div class="form-group">
          <%= f.label :horizontal_recoil, "horizontal_recoil" %>
          <%= f.number_field :horizontal_recoil, {class: "form-control", placeholder: "horizontal_recoil recoil", step: 0.01} %>
        </div>
        <div class="form-group">
          <%= f.label :range_1, "range_1" %>
          <%= f.number_field :range_1, {class: "form-control", placeholder: "range_1", step: 0.01} %>
        </div>


         <div class="form-group">
          <%= f.label :note, "note " %>
          <%= f.text_field :note, {class: "form-control", placeholder: "note", step: 0.01} %>
        </div>
        

  </div>
  <div class="col-md-4">

        <div class="form-group">
          <%= f.label :rpm, "Round Per minute" %>
          <%= f.number_field :rpm, {class: "form-control", placeholder: "round per minute", step: 0.01} %>
        </div>
         <div class="form-group">
          <%= f.label :reload_time, "reload_time" %>
          <%= f.number_field :reload_time, {class: "form-control", placeholder: "reload_time", step: 0.01} %>
        </div>
         <div class="form-group">
          <%= f.label :vertical_recoil_first_10, "vertical_recoil_first_10" %>
          <%= f.number_field :vertical_recoil_first_10, {class: "form-control", placeholder: "vertical_recoil_first_10", step: 0.01} %>
        </div>
        <div class="form-group">
          <%= f.label :horizontal_recoil_first_10, "horizontal_recoil_first_10" %>
          <%= f.number_field :horizontal_recoil_first_10, {class: "form-control", placeholder: "horizontal_recoil_first_10", step: 0.01} %>
        </div>
        <div class="form-group">
          <%= f.label :vertical_recoil_first_20, "vertical_recoil_first_20" %>
          <%= f.number_field :vertical_recoil_first_20, {class: "form-control", placeholder: "vertical_recoil_first_20", step: 0.01} %>
        </div>
        <div class="form-group">
          <%= f.label :horizontal_recoil_first_20, "horizontal_recoil_first_20" %>
          <%= f.number_field :horizontal_recoil_first_20, {class: "form-control", placeholder: "horizontal_recoil_first_20", step: 0.01} %>
        </div>
        
         <div class="form-group">
          <%= f.label :range_2, "range_2" %>
          <%= f.number_field :range_2, {class: "form-control", placeholder: "range_2", step: 0.01} %>
        </div>
         <div class="form-group">
          <%= f.label :range_3, "range_3" %>
          <%= f.number_field :range_3, {class: "form-control", placeholder: "range_3", step: 0.01} %>
        </div>

        <div class="form-group">
          <%= f.label :range_4, "range_4" %>
          <%= f.number_field :range_4, {class: "form-control", placeholder: "range_4", step: 0.01} %>
        </div>

        <div class="form-group">
          <%= f.label :range_3_used, "Range 3 is used ? " %>
          <%= f.check_box :range_3_used %>
        </div>
         <div class="form-group">
          <%= f.label :range_4_used, "Range 4 is used ? " %>
          <%= f.check_box :range_4_used %>
        </div>

       
        <div class="form-group">
          <%= f.label :spread_image, "Basic Spread image" %>
          <%= f.text_field :spread_image, {class: "form-control", placeholder: "spread url"} %>
        </div>
  
  </div>
  <div class="col-md-4">
   <div class="form-group">
          <%= f.label :head_dmg_range_1, "head_dmg_range_1" %>
          <%= f.number_field :head_dmg_range_1, {class: "form-control", placeholder: "head_dmg_range_1"} %>
        </div>
        <div class="form-group">
          <%= f.label :chest_dmg_range_1, "chest_dmg_range_1" %>
          <%= f.number_field :chest_dmg_range_1, {class: "form-control", placeholder: "chest_dmg_range_1"} %>
        </div>
        <div class="form-group">
          <%= f.label :stomach_dmg_range_1, "stomach_dmg_range_1" %>
          <%= f.number_field :stomach_dmg_range_1, {class: "form-control", placeholder: "stomach_dmg_range_1"} %>
        </div>
        <div class="form-group">
          <%= f.label :limbs_dmg_range_1, "limbs_dmg_range_1" %>
          <%= f.number_field :limbs_dmg_range_1, {class: "form-control", placeholder: "limbs_dmg_range_1"} %>
        </div>
        <div class="form-group">
          <%= f.label :head_dmg_range_2, "head_dmg_range_2" %>
          <%= f.number_field :head_dmg_range_2, {class: "form-control", placeholder: "head_dmg_range_2"} %>
        </div>
        <div class="form-group">
          <%= f.label :chest_dmg_range_2, "chest_dmg_range_2" %>
          <%= f.number_field :chest_dmg_range_2, {class: "form-control", placeholder: "chest_dmg_range_2"} %>
        </div>
        <div class="form-group">
          <%= f.label :stomach_dmg_range_2, "stomach_dmg_range_2" %>
          <%= f.number_field :stomach_dmg_range_2, {class: "form-control", placeholder: "stomach_dmg_range_2"} %>
        </div>
        <div class="form-group">
          <%= f.label :limbs_dmg_range_2, "limbs_dmg_range_2" %>
          <%= f.number_field :limbs_dmg_range_2, {class: "form-control", placeholder: "limbs_dmg_range_2"} %>
        </div>
        <div class="form-group">
          <%= f.label :head_dmg_range_3, "head_dmg_range_3" %>
          <%= f.number_field :head_dmg_range_3, {class: "form-control", placeholder: "head_dmg_range_3"} %>
        </div>
        <div class="form-group">
          <%= f.label :chest_dmg_range_3, "chest_dmg_range_3" %>
          <%= f.number_field :chest_dmg_range_3, {class: "form-control", placeholder: "chest_dmg_range_3"} %>
        </div>
        <div class="form-group">
          <%= f.label :stomach_dmg_range_3, "stomach_dmg_range_3" %>
          <%= f.number_field :stomach_dmg_range_3, {class: "form-control", placeholder: "stomach_dmg_range_3"} %>
        </div>
        <div class="form-group">
          <%= f.label :limbs_dmg_range_3, "limbs_dmg_range_3" %>
          <%= f.number_field :limbs_dmg_range_3, {class: "form-control", placeholder: "limbs_dmg_range_3"} %>
        </div>
        <div class="form-group">
          <%= f.label :head_dmg_range_4, "head_dmg_range_4" %>
          <%= f.number_field :head_dmg_range_4, {class: "form-control", placeholder: "head_dmg_range_4"} %>
        </div>
        <div class="form-group">
          <%= f.label :chest_dmg_range_4, "chest_dmg_range_4" %>
          <%= f.number_field :chest_dmg_range_4, {class: "form-control", placeholder: "chest_dmg_range_4"} %>
        </div>
        <div class="form-group">
          <%= f.label :stomach_dmg_range_4, "stomach_dmg_range_4" %>
          <%= f.number_field :stomach_dmg_range_4, {class: "form-control", placeholder: "stomach_dmg_range_4"} %>
        </div>
        <div class="form-group">
          <%= f.label :limbs_dmg_range_4, "limbs_dmg_range_4" %>
          <%= f.number_field :limbs_dmg_range_4, {class: "form-control", placeholder: "limbs_dmg_range_4"} %>
        </div>

  
  </div>
</div>
        
       
       
       
      
       

        

app/views/shared/_hip_fires.html.erb
<div class="recoil-hip">

<ul>

<% hipfireable.each do |hip| %>

<li> data X = <%= hip.xaxis%> , X = <%= hip.yaxis%>, area : <%= (hip.yaxis * hip.xaxis) / 1000 %>
<%= link_to  "delete", api_v1_weapon_hip_fire_path( weapon, hip.id), method: :delete, data:{confirm: "are you sure ?"}, remote: true %>

</li>


<% end %>


</ul>

<h2> Moyenne Spread : <%= average_hip_fire(hipfireable) %> </h2>
<h2> Weapon Value : <%= weapon.hip_fire_cone %> </h2>
<h2> Modifier to report (base - moyenne) : <%= net_hip_fire(hipfireable, weapon.hip_fire_cone) %> </h2>

</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light mb-3">
  

  <%=link_to  image_tag( asset_path("warzoneweapon.png"), width: "150"), root_path, class: "navbar-brand" %>

   <div class="d-lg-none nav-div">
  
         <%= link_to  warzone_weapons_builder_path, data: {turbolinks: false}, class: "nav-link " do %>
            <button class="btn btn-lg btn-outline-dark nav-button"> Weapon Builder </button>
         <% end %>
   
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

 

  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
      <li class="nav-item active">
        <%=link_to  "Weapons builder", warzone_weapons_builder_path, data: {turbolinks: false}, class: "nav-link" %>
      </li>

       <li class="nav-item active">
        <%=link_to  "Weapons Comparison", warzone_weapons_builder_path, data: {turbolinks: false}, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%=link_to  "Meta Weapons", '/', class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%=link_to  "Best Settings", '/', class: "nav-link" %>
      </li>
      <% if user_signed_in? && current_user.admin %>
        <li class="nav-item active">
          <%=link_to  "Admin", admin_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to('Signup', new_user_registration_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        </li>
      <% end %>
    </ul>
</div>
    
  
</nav>